{
 "title": "KMM Scale Tests",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SNOs average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)\n",
     "legendFormat": "Average container CPU usage"
    }
   ]
  },
  {
   "title": "SNOs average RAM usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(cluster:memory_usage_bytes:sum)",
     "legendFormat": "SNO nodes"
    }
   ]
  },
  {
   "title": "HUB average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)\n",
     "legendFormat": "Hub Cluster"
    }
   ]
  },
  {
   "title": "HUB average memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "cluster:memory_usage_bytes:sum", "legendFormat": "Hub Cluster" }
   ]
  },
  {
   "title": "CPU Usage / SNOs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cluster:container_cpu_usage:ratio",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage/SNO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster:memory_usage_bytes:sum{clusterType=\"SNO\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CPU usage from KMM-Hub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"openshift-kmm-hub\"}[1m])) / sum(machine_cpu_cores) * 100",
     "legendFormat": "Rate use of CPU from kmm-hub namespace"
    }
   ]
  },
  {
   "title": "Memory usage from KMM Hub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"openshift-kmm-hub\",container=\"manager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU usage KMM spokes containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum{clusterType=\"SNO\",namespace=\"openshift-kmm\"})",
     "legendFormat": "AVG CPU openshift-kmm namspace"
    }
   ]
  },
  {
   "title": "Average Memory usage KMM spokes containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(namespace:container_memory_usage_bytes:sum{namespace=\"openshift-kmm\"})",
     "legendFormat": "Average RAM usage in spoke KMM containers"
    }
   ]
  },
  {
   "title": "Number of kmm-kmod container at spokes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"openshift-kmm\",pod=~\".*kmod.*\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of kmm-controllers at spokes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"openshift-kmm\",pod=~\".*controller.*\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of SNOs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "acm_managed_cluster_count{}", "legendFormat": "__auto" }
   ]
  }
 ]
}